# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ObscurApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ObscurApp
 rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]


    pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

# very important to have, unless you removed React dependencies for Libraries
# and you rely on Cocoapods to manage it
pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
pod 'Firebase/Core', '~> 5.20.1'
pod 'RSKImageCropper'


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end


end

